language: node_js
node_js:
- 4
- 5
- 6
- node
script:
- npm run test
- npm run lint
deploy:
  provider: heroku
  api_key:
    secure: ChKOJ3QqqsbAuKqXQfOuGJQDHbVdKrOvypX0aCuUfQwlZrGuZmEU4NPgOzKA9hRkU5zSt94xU9RKpofF7Su7JM8AU0iZrx8AoB6MZDZVe7Q7mdKVoj4KrNlLr5POYTbMwbZeuTo6JJYCPQBUsqCjNtIYNtREIz9FCqSbHBYsUbvbnv7zbORtieI0C1S06S68kZ+XvDrhUdhP+eRCATufXvVjyPP2AlvuPEhrnbJ2ZoA4714SP0hZU+bvqGCk/9Dfpbdwf5sdYY0yhtJPo4t59yO7qeS3oVZOx4YxJhpuS5bTiMk14o8TuqAqHxckECQWpx4kDaC/tk5lq8MLGK4MgHbH6z/j9kbFjS6NVEusybEdMQKGy4h66AypQ3P/xwqRbxlfuL/DI4jCo0DU3/jOJUmTU1vCtVm+MIHzKu7fMk/Ih3pmelOkqbfKzVdNdW7UO+DcdIlZOvyx+f+IHqSNEAH3d+Vw38fyaUth8GJTppGEYlmpQxQhy9E6Y2Cx6bdfrLwGPtWQBuSVASb9bXizMGfhrAZJ331w3V5ejuor4JtMT9HjReIOYJjpNQz4EKANgCFqWN7tlPgiUDFCuNJHZMPBO3DEUX+KsUeK1I0vwajsfIfu9X+epSPoRsJBXIJ3m6Rv/V/BMD62H9Xh/FcsHyhC4oBApB1sZTo7JkQOs8o=
  app: code-cafe-io
  on:
    repo: LunaMinds/code-cafe
